version: '3'

services:
  ctf-scoreboard:
    build: .
    volumes:
      - ./static:/static
      - ./templates:/templates
    environment:
      - CTFD_API_KEY=ctfd_2c71a65dc478092a47cdebf982b250337ba33b3f15505001fd0dbec10f62b89e
      - CTFD_API_URL=https://krductf.ru/api/v1/scoreboard
    networks:
      ctfnet:
        ipv4_address: 10.0.0.21

networks:
  ctfnet:
    external: true
