services:
  ctf-scoreboard:
    build: .
    volumes:
      - ./static:/static
      - ./templates:/templates
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - CTFD_API_KEY=
      - CTFD_URL=https://krductf.ru
