version: '3'

services:
  ctf-scoreboard:
    build: .
    volumes:
      - ./static:/static
      - ./templates:/templates
    environment:
      - PYTHONUNBUFFERED=1
      - CTFD_API_KEY=
      - CTFD_URL=https://krductf.ru
    networks:
      ctfnet:
        ipv4_address: 10.0.0.21

networks:
  ctfnet:
    external: true
